FROM aamservices/opencart:3.0.3.6

COPY opencart-extension/catalog/controller/api/unisouk/ \
     /var/www/html/catalog/controller/api/unisouk/

COPY opencart-extension/catalog/model/api/unisouk/ \
     /var/www/html/catalog/model/api/unisouk/

COPY opencart-extension/catalog/language/en-gb/api/unisouk/ \
     /var/www/html/catalog/language/en-gb/api/unisouk/
